### ISSUE TITLE
fatal     HttpError: Resource not accessible by integration 

### ISSUE THREAD

**Issue by gucio321** [Decathlon/pull-request-labeler-action#41]
Hi there!
I added labeler, but it crashes with a following error:
```
✖  fatal     HttpError: Resource not accessible by integration 
    at response.text.then.message (/app/node_modules/@octokit/request/dist-node/index.js:66:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
workflow run: https://github.com/OpenDiablo2/OpenDiablo2/pull/1120/checks?check_run_id=2435495674
workflow file: https://github.com/OpenDiablo2/OpenDiablo2/blob/eb470533c42e2595f409b0b98caf020b4d361d43/.github/workflows/labeler.yaml

I suppose, that this happens if someone without merge access opens the pull request.

**Comment by gucio321** [comment]
also, I'm using this workflow on my own repository: https://github.com/gucio321/tic-tac-go
When I'm opening a pull request there, it works fine.

**Comment by gucio321** [comment]
the same error on my private repo:
Pull request opened by dependabot: https://github.com/gucio321/tic-tac-go/pull/126
workflow: https://github.com/gucio321/tic-tac-go/pull/126/checks?check_run_id=2437178430

**Comment by Sophist-UK** [comment]
Ditto!!!!

**Comment by lucaskjaero** [comment]
Hi @gucio321 and @Sophist-UK, is your workflow using `pull_request` to as a trigger? There's been some github actions changes that don't allow dependabot to access `secrets.GITHUB_TOKEN`. You can allow this by switching to using `pull_request_target` instead.
